### ISSUE TITLE
between/3

### ISSUE THREAD

**Issue by guregu** [ichiban/prolog#163]
I tried implementing between/3: https://github.com/guregu/predicates/blob/master/between.go
Would you be interested in adding it here? I imagine this could be implemented in Prolog instead of natively pretty easily 😇.

I wanted to make it lazily create the choice points so I tried using engine.Repeat, but I'm not sure if I did it right.
I also added a check for overflowing but I'm not sure if we want that.

P.S. @ichiban, thank you very much for this project. I am having a lot of fun using it. It has led me down the Prolog rabbit-hole and changed my perspective on programming.

**Comment by triska** [comment]
I strongly recommend to use the interface of `between/3` as implemented in SICStus Prolog and Scryer Prolog:

https://sicstus.sics.se/sicstus/docs/4.6.0/html/sicstus/lib_002dbetween.html

Note that (regarded as types) **all arguments must be integers**. This ensures the following important property: 

<blockquote>
<tt>between/3</tt> <b>always terminates</b>.
</blockquote>

This property is very valuable when you are doing termination analysis of Prolog programs.

**Comment by guregu** [comment]
Thank you for the tip @triska, I've updated my implementation to require that all arguments be integers. This way feels much cleaner 🙂

**Comment by ichiban** [comment]
Great work, @guregu!
`between/3` is a common predicate this library lacks and it should be implemented in Go for a better performance!
I'll be very happy if you could make a PR for it.

I second that `between/3` should follow the Prologue for Prolog as @triska pointed out. I think this library should be minimal yet ISO / de facto standard compliant, and also open to extension!

the `infinite` extension should be outside of this library and I'll happily point to your project in README.
Also, I think the same thing can be done within ISO standard like this:

```go
current_prolog_flag(max_integer, Max), between(Lower, Max, X).
```

Some points I found in your code:

`engine.typeErrorInteger()` should've been exposed. My bad 🙇 

https://github.com/guregu/predicates/blob/9978b67b8741c7f1dbe39fceaf1fbb04f0438ed8/between.go#L23

I'm currently working on refactoring arithmetic operators and about to include `engine.ErrIntOverflow`.

https://github.com/guregu/predicates/blob/9978b67b8741c7f1dbe39fceaf1fbb04f0438ed8/between.go#L48

While working on built-in predicates, I've rarely used `engine.Bool(true)` since it means "succeeded and no need to execute the rest of the body." Perhaps `k(env)`, "succeeded and keep on the rest of the body?"

https://github.com/guregu/predicates/blob/9978b67b8741c7f1dbe39fceaf1fbb04f0438ed8/between.go#L50

P.S. The hole you went down is the same hole I accidentally fell into a few minutes before. Where are we now? Let's look around and enjoy together!

**Comment by guregu** [comment]
Thank you, @ichiban! 
I will make a PR soon 👍 

About `engine.Bool(true)`, my intention there was to 'break out' of the Repeat loop. I'm attempting to lazily iterate through the successive integers instead of creating N continuations ahead of time and passing them to `Delay`. Is there a better way to do this? If I return `Bool(false)` or call `k(env)` there it loops forever. 
I imagine I'm probably abusing `Repeat` here. Let me know the proper way and I'll fix it for the PR 🙇

**Comment by triska** [comment]
Note that `max_integer` is only defined if `bounded` is `true`:

<pre>
<b>7.11.1.2 Flag: max_integer</b>

...

Description: If the value of flag bounded is true then
the value of this flag is the largest integer such that
integer arithmetic is performed correctly if the operands
and mathematically correct result all lie in the closed
interval (min_integer, max_integer).
</pre>

To reliably and portably obtain the sequence `0, 1, 2, ...`, `length/2` is very useful:

<pre>
?- length(_, N).
</pre>

An implementation can implement this very efficiently, by avoiding the generation of list skeletons if the first argument is an anonymous variable.

**Comment by ichiban** [comment]
@guregu Control flow is really hard! I pulled my hair out so many times. I can't tell if your implementation with `engine.Repeat()` does it right or not just by looking at the code!

After struggling with control flow so many times, I realized that recursion is the best way to iterate.
Go doesn't optimize recursions so tell the caller (which does `.Force()` ) to do the recursion call with `engine.Delay()`.

https://go.dev/play/p/YIvnQDQKd29

```go
package main

import (
	"context"
	"fmt"

	"github.com/ichiban/prolog/engine"
)

func main() {
	_, _ = iter(10)
	_, _ = iterPromise(10).Force(context.Background())
}

// Simple recursion. This leads to a stack overflow for a large enough count.
func iter(count int) (bool, error) {
	// Termination condition.
	if count <= 0 {
		return true, nil
	}

	// First, print the counter.
	fmt.Printf("count = %d\n", count)

	// Then, proceed to the next step.
	return iter(count - 1)
}

// Recursion with trampolines. This won't cause a stack overflow.
func iterPromise(count int) *engine.Promise {
	// Termination condition.
	if count <= 0 {
		return engine.Bool(true)
	}

	// Tell the caller there're 2 choices.
	return engine.Delay(func(context.Context) *engine.Promise {
		// Print the counter.
		fmt.Printf("count = %d\n", count)

		// Then, tell the caller this branch led to a dead end and try another.
		return engine.Bool(false)
	}, func(context.Context) *engine.Promise {
		// Tell the caller this branch leads to the next step.
		return iterPromise(count - 1)
	})
}
```

**Comment by guregu** [comment]
Awesome release! Thanks for the shoutout.
