### ISSUE TITLE
nth0/3 is not correct

### ISSUE THREAD

**Issue by triska** [ichiban/prolog#176]
I tried the current definition of [`nth0/3`](https://github.com/ichiban/prolog/blob/08fb802684ffe7d28dac2888121cce02b282ff18/bootstrap.pl#L241) with Scryer Prolog, and get for example:

<pre>
<b>?- nth0(N, "abc", E).</b>
   N = 0, E = a.
</pre>

Expected:

<pre>
<b>?- nth0(N, "abc", E).</b>
   N = 0, E = a
;  N = 1, E = b
;  N = 2, E = c
;  false.
</pre>

**Comment by ichiban** [comment]
@triska Thank you very much for pointing out this! I reimplemented `nth0/3` and `nth1/3` so that they can handle unbounded `N` correctly.

Since I did it in Go, it's impossible to just copy and paste it to another Prolog processor and see the result.
Here's a result from `1pl`, my experimental top level for testing purposes only:

```console
$ go run cmd/1pl/main.go 
?- set_prolog_flag(double_quotes, chars).
true.
?- nth0(N, "abc", E).
N = 0,
E = a;
N = 1,
E = b;
N = 2,
E = c;
?- 
```

**Comment by triska** [comment]
Thank you a lot, I am closing this issue!

One suggestion: Would you please consider setting `double_quotes` to `chars` **by default**? This would make string handling a lot more convenient and readable, and improve portability of your system with the three newest Prolog systems: Scryer, Tau and Trealla&nbsp;Prolog, all of which set `double_quotes` to `chars` already by default.
