### ISSUE TITLE
How much memory does Ichiban or Go require?

### ISSUE THREAD

**Issue by UWN** [ichiban/prolog#218]
Since it is now the time of looping queries, I need some memory limit. Otherwise, my old laptop becomes unusable for me. On all systems so far, it was possible to run the system with: `ulimit -v 99999` (that's easy to type). But with Ichiban I get:

```
ulrich@p0:/opt/gupu/ichiban-prolog$ ulimit -v 500000
ulrich@p0:/opt/gupu/ichiban-prolog$ export PATH=/usr/local/go/bin:$PATH
ulrich@p0:/opt/gupu/ichiban-prolog$ $(go env GOPATH)/bin/1pl
fatal error: failed to reserve page summary memory

runtime stack:
runtime.throw({0x9f3861?, 0x40f3e5?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0x7ffe6d1dc438 sp=0x7ffe6d1dc408 pc=0x435ad1
...
```

**Comment by ichiban** [comment]
When I run a simple test case with memory profiling in my IDE (goland), it says around 27MB(!?) are allocated. It also says the vast majority of the memory consumption comes from the parser. I'll reduce the memory consumption there.

```go
func TestNew2(t *testing.T) {
	p := New(nil, nil)
	assert.NotNil(t, p)
}
```

**Comment by UWN** [comment]
Note that in all probability this is not your fault. It seems that Go wants to grab control over memory. After all, I even tried `ulimit -v 500000` which is much more than generous. Maybe try it with a minimal Go program and see if the same happens there too.

**Comment by guregu** [comment]
I did some research into this. Looks like Go tries to reserve a ton of virtual memory upfront and `ulimit -v` is essentially incompatible with it. There's an [accepted proposal](https://github.com/golang/go/issues/48409) for a soft memory limit that looks like it might land in the next version of Go.

I think we could implement a quick workaround for limiting memory of `1pl`.
Here's my idea:
- Take memory limit as a command line argument
- If memory limit is set:
  - Each time a query is run, start up an additional 'watchdog' goroutine that monitors heap size every second or so (using [runtime.ReadMemStats](https://pkg.go.dev/runtime#ReadMemStats))
  - If the heap size > memory limit, cancel the query context, stopping the query

I don't think this will work 100% because instability from OOM stuff might prevent the watchdog goroutine from working properly, but with a little bit of experimentation I think it might be good enough to solve our problem here.
The related Go issues are more concerned with keeping long-running processes alive, but for us we only care about canceling queries and failing our tests, so our use case is a bit simpler.

**Comment by UWN** [comment]
Also looking into `/proc/PID/maps` doesnt show anything voracious. So it seems rather the logic of Go in general that interferes...

**Comment by ichiban** [comment]
Did some very basic memory optimization on the parser. @UWN Could you try the `main` branch, please?

**Comment by UWN** [comment]
On another machine its `ulimit -v 800000` which works.
